dist: trusty
language: node_js
node_js:
- stable
os:
- windows
script:
- npm run lint
- run build:dev
- npm run coverage
- npm run check-coverage
after_success:
- npm run report-coverage
branches:
 only:
 - master
notifications:
 email:
   recipients:
     - rrongan@gmail.com      # use your own
   on_success: never        # default: change
   on_failure: always       # default: always
install:            # NEW
- wget -N https://chromedriver.storage.googleapis.com/2.30/chromedriver_linux64.zip -P ~/
- unzip ~/chromedriver_linux64.zip -d ~/
- rm ~/chromedriver_linux64.zip
- sudo mv -f ~/chromedriver /usr/local/share/
- sudo chmod +x /usr/local/share/chromedriver
- sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
- npm install
before_script:      # NEW
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3
deploy:
  provider: heroku
  api_key:
    secure: "98dbaf18-6ab3-437e-b95a-adcc93494355"